source_group(include REGULAR_EXPRESSION .*include/.*)
source_group(include\\detail REGULAR_EXPRESSION .*include/.*/detail/.*)
source_group(include\\detail\\subject REGULAR_EXPRESSION .*include/.*/detail/subject/.*)
source_group(src REGULAR_EXPRESSION .*src/.*)
source_group(src\\detail REGULAR_EXPRESSION .*src/detail/.*)